# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"
tasks:
  default:
    cmds:
      - task: build

  build:
    run: once
    vars:
      MODE: '{{.MODE | default "debug"}}'
      QUIET: '{{.QUIET | default "false"}}'
    cmds:
      - cargo build {{if eq .MODE "release"}}--release{{end}} {{if eq .QUIET "true"}}2>/dev/null{{end}}

  link:
    vars:
      QUIET: '{{.QUIET | default "false"}}'
    deps:
      - task: build
        vars: { QUIET: "{{.QUIET}}" }
    dir: "{{.ROOT_DIR}}/bin"
    cmds:
      - mkdir -p .
      - ln -sf ../crates/mdlr-extract-rust/target/debug/mdlr-extract-rust .
