# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"
includes:
  mdlr-extract-rust:
    taskfile: ./crates/mdlr-extract-rust
    dir: ./crates/mdlr-extract-rust

tasks:
  default:
    cmds:
      - task: build

  run:
    deps: [build]
    cmd: mdlr {{.CLI_ARGS}}

  build:
    deps:
      - task: mdlr-extract-rust:build
        vars:
          MODE: "{{.MODE}}"
          QUIET: "{{.QUIET}}"
    vars:
      MODE: '{{.MODE | default "debug"}}'
      QUIET: '{{.QUIET | default "false"}}'
    cmds:
      - cargo build {{if eq .MODE "release"}}--release{{end}} {{if eq .QUIET "true"}}2>/dev/null{{end}}

  link:
    vars:
      QUIET: '{{.QUIET | default "false"}}'
    deps:
      - task: mdlr-extract-rust:link
        vars:
          QUIET: "{{.QUIET}}"
      - task: build
        vars: { QUIET: "{{.QUIET}}" }
    dir: bin
    cmds:
      - ln -sf ../target/debug/mdlr .

  check:
    deps:
      - task: link
        vars: { QUIET: "true" }
    cmds:
      - mdlr check

  install:
    dir: "{{.ROOT_DIR}}"
    cmds:
      - cargo install --path . --root $HOME/.local
